language: c
sudo: false

os:
  - linux

env:
  global:
    - DEVKITPRO=$HOME/devkitPro
    - DEVKITPPC=${DEVKITPRO}/devkitPPC

cache:
  directories:
    - ${DEVKITPRO}

addons:
  apt:
    packages:
    - p7zip-full

before_install:
  - mkdir -p "${DEVKITPRO}"
  - wget http://download.sourceforge.net/devkitpro/devkitPPC_r29-1-x86_64-linux.tar.bz2 -O devkitPPC-linux.tar.bz2
  - wget https://github.com/Maschell/dynamic_libs/archive/lib.tar.gz -O dynamic_libs.tar.gz
  - wget https://github.com/Maschell/libutils/archive/master.tar.gz -O libutils.tar.gz

install:
  - tar -xjf devkitPPC-linux.tar.bz2 -C ${DEVKITPRO}/
  - tar -xzvf dynamic_libs.tar.gz
  - tar -xzvf libutils.tar.gz
  - 7z x -y ./dynamic_libs-lib/libs/portlibs.zip -o${DEVKITPRO}
  - (cd dynamic_libs-lib && make -j8 && make install)
  - (cd libutils-master && make -j8 && make install)

script:
- make
- (cd loader && make)
- (cd example_plugin && make)

before_deploy:
- mkdir -p "wiiu/apps/wiiupluginloader"
- commit="$(git rev-parse --short=7 HEAD)"
- (cd loader && chmod +x gitrev.sh)
- (cd loader && versiontag="$(./gitrev.sh)")
- (cd loader && make)
- cp loader/meta/* wiiu/apps/wiiupluginloader
- cp loader/wiiupluginloader.elf wiiu/apps/wiiupluginloader
- zip -r wiiupluginloader_$versiontag.zip wiiu example_plugin/bin/example_plugin.mod
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=WiiUPluginLoader-$versiontag
- commitLog="$(git log -1 --pretty=%B)"
- commitMessage="$(echo -e "-\n" && echo "WiiUPluginLoader nightly build. Not a stable release. Expect bugs!" && echo -e "\nCommitlog:\n")"
- git tag $GIT_TAG -a -m "$commitMessage" -m "$commitLog"
- git push --quiet https://$GITHUBKEY@github.com/Maschell/WiiUPluginSystem $GIT_TAG > /dev/null 2>&1

deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  api_key:
    secure: "PmwfPLKcbTnoymO2hJ68clJqQimMPfsanpA2vBSVgI7yHfsYkBJ4r9+a+7Fk6flPbVFCtWPFG+l/Tequ3UFOF7oUGmZ8HDjn7GHTLoApeqR7xFayGIlLNUvt5d/G2z47VNepDRHCjuXmEPuf4IcsXgZPO2LPXLxEConc0E+HtuFO1ne21mP1lEsFKuTkuWhl9gcGgjGti6MuBHYtD5qVfDmxgE3x7Io9Gps2Tl57OY4/CIFzxgp9R4c2r7LVhlkUs5V+Zu8l8Ip7MFZgz/u0yKRpCmCv+DTR2s/ALYFznLVMcEf8twK2ik/AryLoMOJ1tfNs1nW95KggMCM6n/q3puZl89rO8PJIMvrppo5Fi1uxLHeGmixoFqJ2Q4Kn4jPJjlkezjkcua24vO1aUl7XskUdXDFGhXxHIno2v7r25kKc7UxLk02UvcujELxc8dZOkbzAo+nHDRWV72U1b3TuE/Rjtd3/6rS0JX5fP7odvfdbKLn/cLkYPbJ+poBKjEYOrNeGFhBCa4XK5qS4O5Fj2g2gqjgE4XIe1ieBo7V6yHElxBbonfbWLWY8/B4oGppAZR+il7uAnPfuH7LUN6IY+GYSda2Yeo8SuW/z0H/f8xRB1z0vTZCAP+M6sLrjSOGq2bi2ZLuwwg5TtL1j7OSHwYm4fo8cGh190I1youajuf0="
  file: WiiUPluginLoader$versiontag.zip
  on:
    repo: Maschell/WiiUPluginSystem
    tags: false
    all_branches: true